// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/api/policy_instance.proto

// Protobuf Java Version: 3.25.3
package com.aserto.authorizer.v2.api;

public final class PolicyInstanceProto {
  private PolicyInstanceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_PolicyInstance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_PolicyInstance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.aserto/authorizer/v2/api/policy_instan" +
      "ce.proto\022\030aserto.authorizer.v2.api\"O\n\016Po" +
      "licyInstance\022\022\n\004name\030\001 \001(\tR\004name\022)\n\016inst" +
      "ance_label\030\002 \001(\tB\002\030\001R\rinstanceLabelB\371\001\n\034" +
      "com.aserto.authorizer.v2.apiB\023PolicyInst" +
      "anceProtoP\001Z@github.com/aserto-dev/go-au" +
      "thorizer/aserto/authorizer/v2/api;api\242\002\004" +
      "AAVA\252\002\030Aserto.Authorizer.V2.Api\312\002\030Aserto" +
      "\\Authorizer\\V2\\Api\342\002$Aserto\\Authorizer\\V" +
      "2\\Api\\GPBMetadata\352\002\033Aserto::Authorizer::" +
      "V2::Apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aserto_authorizer_v2_api_PolicyInstance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aserto_authorizer_v2_api_PolicyInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_PolicyInstance_descriptor,
        new java.lang.String[] { "Name", "InstanceLabel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
