// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.DecisionTreeOptions}
 */
public final class DecisionTreeOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.DecisionTreeOptions)
    DecisionTreeOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DecisionTreeOptions.newBuilder() to construct.
  private DecisionTreeOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DecisionTreeOptions() {
    pathSeparator_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DecisionTreeOptions();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_DecisionTreeOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_DecisionTreeOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.DecisionTreeOptions.class, com.aserto.authorizer.v2.DecisionTreeOptions.Builder.class);
  }

  public static final int PATH_SEPARATOR_FIELD_NUMBER = 1;
  private int pathSeparator_ = 0;
  /**
   * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
   * @return The enum numeric value on the wire for pathSeparator.
   */
  @java.lang.Override public int getPathSeparatorValue() {
    return pathSeparator_;
  }
  /**
   * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
   * @return The pathSeparator.
   */
  @java.lang.Override public com.aserto.authorizer.v2.PathSeparator getPathSeparator() {
    com.aserto.authorizer.v2.PathSeparator result = com.aserto.authorizer.v2.PathSeparator.forNumber(pathSeparator_);
    return result == null ? com.aserto.authorizer.v2.PathSeparator.UNRECOGNIZED : result;
  }

  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.DecisionTreeOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.DecisionTreeOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.DecisionTreeOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.DecisionTreeOptions)
      com.aserto.authorizer.v2.DecisionTreeOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_DecisionTreeOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_DecisionTreeOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.DecisionTreeOptions.class, com.aserto.authorizer.v2.DecisionTreeOptions.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.DecisionTreeOptions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pathSeparator_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_DecisionTreeOptions_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.DecisionTreeOptions getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.DecisionTreeOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.DecisionTreeOptions build() {
      com.aserto.authorizer.v2.DecisionTreeOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.DecisionTreeOptions buildPartial() {
      com.aserto.authorizer.v2.DecisionTreeOptions result = new com.aserto.authorizer.v2.DecisionTreeOptions(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aserto.authorizer.v2.DecisionTreeOptions result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pathSeparator_ = pathSeparator_;
      }
    }

    private int bitField0_;

    private int pathSeparator_ = 0;
    /**
     * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
     * @return The enum numeric value on the wire for pathSeparator.
     */
    @java.lang.Override public int getPathSeparatorValue() {
      return pathSeparator_;
    }
    /**
     * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
     * @param value The enum numeric value on the wire for pathSeparator to set.
     * @return This builder for chaining.
     */
    public Builder setPathSeparatorValue(int value) {
      pathSeparator_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
     * @return The pathSeparator.
     */
    @java.lang.Override
    public com.aserto.authorizer.v2.PathSeparator getPathSeparator() {
      com.aserto.authorizer.v2.PathSeparator result = com.aserto.authorizer.v2.PathSeparator.forNumber(pathSeparator_);
      return result == null ? com.aserto.authorizer.v2.PathSeparator.UNRECOGNIZED : result;
    }
    /**
     * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
     * @param value The pathSeparator to set.
     * @return This builder for chaining.
     */
    public Builder setPathSeparator(com.aserto.authorizer.v2.PathSeparator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      pathSeparator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.aserto.authorizer.v2.PathSeparator path_separator = 1 [json_name = "pathSeparator"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPathSeparator() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pathSeparator_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.DecisionTreeOptions)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.DecisionTreeOptions)
  private static final com.aserto.authorizer.v2.DecisionTreeOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.DecisionTreeOptions();
  }

  public static com.aserto.authorizer.v2.DecisionTreeOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DecisionTreeOptions>
      PARSER = new com.google.protobuf.AbstractParser<DecisionTreeOptions>() {
    @java.lang.Override
    public DecisionTreeOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DecisionTreeOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DecisionTreeOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.DecisionTreeOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

