// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.ListPoliciesRequest}
 */
public final class ListPoliciesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.ListPoliciesRequest)
    ListPoliciesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListPoliciesRequest.newBuilder() to construct.
  private ListPoliciesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListPoliciesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListPoliciesRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.ListPoliciesRequest.class, com.aserto.authorizer.v2.ListPoliciesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FIELD_MASK_FIELD_NUMBER = 1;
  private com.google.protobuf.FieldMask fieldMask_;
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   * @return Whether the fieldMask field is set.
   */
  @java.lang.Override
  public boolean hasFieldMask() {
    return fieldMask_ != null;
  }
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   * @return The fieldMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getFieldMask() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
    return getFieldMask();
  }

  public static final int POLICY_INSTANCE_FIELD_NUMBER = 2;
  private com.aserto.authorizer.v2.api.PolicyInstance policyInstance_;
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   * @return Whether the policyInstance field is set.
   */
  @java.lang.Override
  public boolean hasPolicyInstance() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   * @return The policyInstance.
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.PolicyInstance getPolicyInstance() {
    return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
  }
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder getPolicyInstanceOrBuilder() {
    return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.ListPoliciesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.ListPoliciesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.ListPoliciesRequest)
      com.aserto.authorizer.v2.ListPoliciesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.ListPoliciesRequest.class, com.aserto.authorizer.v2.ListPoliciesRequest.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.ListPoliciesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPolicyInstanceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = null;
      } else {
        fieldMask_ = null;
        fieldMaskBuilder_ = null;
      }
      if (policyInstanceBuilder_ == null) {
        policyInstance_ = null;
      } else {
        policyInstanceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.ListPoliciesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest build() {
      com.aserto.authorizer.v2.ListPoliciesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest buildPartial() {
      com.aserto.authorizer.v2.ListPoliciesRequest result = new com.aserto.authorizer.v2.ListPoliciesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (fieldMaskBuilder_ == null) {
        result.fieldMask_ = fieldMask_;
      } else {
        result.fieldMask_ = fieldMaskBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (policyInstanceBuilder_ == null) {
          result.policyInstance_ = policyInstance_;
        } else {
          result.policyInstance_ = policyInstanceBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private com.google.protobuf.FieldMask fieldMask_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> fieldMaskBuilder_;
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     * @return Whether the fieldMask field is set.
     */
    public boolean hasFieldMask() {
      return fieldMaskBuilder_ != null || fieldMask_ != null;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     * @return The fieldMask.
     */
    public com.google.protobuf.FieldMask getFieldMask() {
      if (fieldMaskBuilder_ == null) {
        return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      } else {
        return fieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder setFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldMask_ = value;
        onChanged();
      } else {
        fieldMaskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder setFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = builderForValue.build();
        onChanged();
      } else {
        fieldMaskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder mergeFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (fieldMask_ != null) {
          fieldMask_ =
            com.google.protobuf.FieldMask.newBuilder(fieldMask_).mergeFrom(value).buildPartial();
        } else {
          fieldMask_ = value;
        }
        onChanged();
      } else {
        fieldMaskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder clearFieldMask() {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = null;
        onChanged();
      } else {
        fieldMask_ = null;
        fieldMaskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public com.google.protobuf.FieldMask.Builder getFieldMaskBuilder() {
      
      onChanged();
      return getFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
      if (fieldMaskBuilder_ != null) {
        return fieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return fieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      }
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getFieldMaskFieldBuilder() {
      if (fieldMaskBuilder_ == null) {
        fieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getFieldMask(),
                getParentForChildren(),
                isClean());
        fieldMask_ = null;
      }
      return fieldMaskBuilder_;
    }

    private com.aserto.authorizer.v2.api.PolicyInstance policyInstance_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder> policyInstanceBuilder_;
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     * @return Whether the policyInstance field is set.
     */
    public boolean hasPolicyInstance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     * @return The policyInstance.
     */
    public com.aserto.authorizer.v2.api.PolicyInstance getPolicyInstance() {
      if (policyInstanceBuilder_ == null) {
        return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
      } else {
        return policyInstanceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder setPolicyInstance(com.aserto.authorizer.v2.api.PolicyInstance value) {
      if (policyInstanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        policyInstance_ = value;
        onChanged();
      } else {
        policyInstanceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder setPolicyInstance(
        com.aserto.authorizer.v2.api.PolicyInstance.Builder builderForValue) {
      if (policyInstanceBuilder_ == null) {
        policyInstance_ = builderForValue.build();
        onChanged();
      } else {
        policyInstanceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder mergePolicyInstance(com.aserto.authorizer.v2.api.PolicyInstance value) {
      if (policyInstanceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            policyInstance_ != null &&
            policyInstance_ != com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance()) {
          policyInstance_ =
            com.aserto.authorizer.v2.api.PolicyInstance.newBuilder(policyInstance_).mergeFrom(value).buildPartial();
        } else {
          policyInstance_ = value;
        }
        onChanged();
      } else {
        policyInstanceBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder clearPolicyInstance() {
      if (policyInstanceBuilder_ == null) {
        policyInstance_ = null;
        onChanged();
      } else {
        policyInstanceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public com.aserto.authorizer.v2.api.PolicyInstance.Builder getPolicyInstanceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPolicyInstanceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder getPolicyInstanceOrBuilder() {
      if (policyInstanceBuilder_ != null) {
        return policyInstanceBuilder_.getMessageOrBuilder();
      } else {
        return policyInstance_ == null ?
            com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
      }
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder> 
        getPolicyInstanceFieldBuilder() {
      if (policyInstanceBuilder_ == null) {
        policyInstanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder>(
                getPolicyInstance(),
                getParentForChildren(),
                isClean());
        policyInstance_ = null;
      }
      return policyInstanceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.ListPoliciesRequest)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.ListPoliciesRequest)
  private static final com.aserto.authorizer.v2.ListPoliciesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.ListPoliciesRequest();
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPoliciesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListPoliciesRequest>() {
    @java.lang.Override
    public ListPoliciesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListPoliciesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPoliciesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

