// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.ListPoliciesResponse}
 */
public final class ListPoliciesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.ListPoliciesResponse)
    ListPoliciesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListPoliciesResponse.newBuilder() to construct.
  private ListPoliciesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListPoliciesResponse() {
    result_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListPoliciesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.ListPoliciesResponse.class, com.aserto.authorizer.v2.ListPoliciesResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private java.util.List<com.aserto.authorizer.v2.api.Module> result_;
  /**
   * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public java.util.List<com.aserto.authorizer.v2.api.Module> getResultList() {
    return result_;
  }
  /**
   * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aserto.authorizer.v2.api.ModuleOrBuilder> 
      getResultOrBuilderList() {
    return result_;
  }
  /**
   * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.Module getResult(int index) {
    return result_.get(index);
  }
  /**
   * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.ModuleOrBuilder getResultOrBuilder(
      int index) {
    return result_.get(index);
  }

  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.ListPoliciesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.ListPoliciesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.ListPoliciesResponse)
      com.aserto.authorizer.v2.ListPoliciesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.ListPoliciesResponse.class, com.aserto.authorizer.v2.ListPoliciesResponse.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.ListPoliciesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
      } else {
        result_ = null;
        resultBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesResponse_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesResponse getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.ListPoliciesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesResponse build() {
      com.aserto.authorizer.v2.ListPoliciesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesResponse buildPartial() {
      com.aserto.authorizer.v2.ListPoliciesResponse result = new com.aserto.authorizer.v2.ListPoliciesResponse(this);
      int from_bitField0_ = bitField0_;
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<com.aserto.authorizer.v2.api.Module> result_ =
      java.util.Collections.emptyList();
    private void ensureResultIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        result_ = new java.util.ArrayList<com.aserto.authorizer.v2.api.Module>(result_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.authorizer.v2.api.Module, com.aserto.authorizer.v2.api.Module.Builder, com.aserto.authorizer.v2.api.ModuleOrBuilder> resultBuilder_;

    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public java.util.List<com.aserto.authorizer.v2.api.Module> getResultList() {
      if (resultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(result_);
      } else {
        return resultBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public int getResultCount() {
      if (resultBuilder_ == null) {
        return result_.size();
      } else {
        return resultBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public com.aserto.authorizer.v2.api.Module getResult(int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);
      } else {
        return resultBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(
        int index, com.aserto.authorizer.v2.api.Module value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
      } else {
        resultBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(
        int index, com.aserto.authorizer.v2.api.Module.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder addResult(com.aserto.authorizer.v2.api.Module value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
      } else {
        resultBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder addResult(
        int index, com.aserto.authorizer.v2.api.Module value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(index, value);
        onChanged();
      } else {
        resultBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder addResult(
        com.aserto.authorizer.v2.api.Module.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder addResult(
        int index, com.aserto.authorizer.v2.api.Module.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends com.aserto.authorizer.v2.api.Module> values) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
      } else {
        resultBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public Builder removeResult(int index) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.remove(index);
        onChanged();
      } else {
        resultBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public com.aserto.authorizer.v2.api.Module.Builder getResultBuilder(
        int index) {
      return getResultFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public com.aserto.authorizer.v2.api.ModuleOrBuilder getResultOrBuilder(
        int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);  } else {
        return resultBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public java.util.List<? extends com.aserto.authorizer.v2.api.ModuleOrBuilder> 
         getResultOrBuilderList() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(result_);
      }
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public com.aserto.authorizer.v2.api.Module.Builder addResultBuilder() {
      return getResultFieldBuilder().addBuilder(
          com.aserto.authorizer.v2.api.Module.getDefaultInstance());
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public com.aserto.authorizer.v2.api.Module.Builder addResultBuilder(
        int index) {
      return getResultFieldBuilder().addBuilder(
          index, com.aserto.authorizer.v2.api.Module.getDefaultInstance());
    }
    /**
     * <code>repeated .aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
     */
    public java.util.List<com.aserto.authorizer.v2.api.Module.Builder> 
         getResultBuilderList() {
      return getResultFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.authorizer.v2.api.Module, com.aserto.authorizer.v2.api.Module.Builder, com.aserto.authorizer.v2.api.ModuleOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aserto.authorizer.v2.api.Module, com.aserto.authorizer.v2.api.Module.Builder, com.aserto.authorizer.v2.api.ModuleOrBuilder>(
                result_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.ListPoliciesResponse)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.ListPoliciesResponse)
  private static final com.aserto.authorizer.v2.ListPoliciesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.ListPoliciesResponse();
  }

  public static com.aserto.authorizer.v2.ListPoliciesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPoliciesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListPoliciesResponse>() {
    @java.lang.Override
    public ListPoliciesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListPoliciesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPoliciesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.ListPoliciesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

