// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/api/decision_logs.proto

package com.aserto.authorizer.v2.api;

public final class DecisionLogsProto {
  private DecisionLogsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_Decision_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_Decision_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_Decision_OutcomesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_Decision_OutcomesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_Decision_AnnotationsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_Decision_AnnotationsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_DecisionUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_DecisionUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_authorizer_v2_api_DecisionPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_authorizer_v2_api_DecisionPolicy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,aserto/authorizer/v2/api/decision_logs" +
      ".proto\022\030aserto.authorizer.v2.api\032\034google" +
      "/protobuf/struct.proto\032\037google/protobuf/" +
      "timestamp.proto\032-aserto/authorizer/v2/ap" +
      "i/policy_context.proto\032/aserto/authorize" +
      "r/v2/api/identity_context.proto\"\275\004\n\010Deci" +
      "sion\022\016\n\002id\030\001 \001(\tR\002id\0228\n\ttimestamp\030\002 \001(\0132" +
      "\032.google.protobuf.TimestampR\ttimestamp\022\022" +
      "\n\004path\030\003 \001(\tR\004path\022:\n\004user\030\004 \001(\0132&.asert" +
      "o.authorizer.v2.api.DecisionUserR\004user\022@" +
      "\n\006policy\030\005 \001(\0132(.aserto.authorizer.v2.ap" +
      "i.DecisionPolicyR\006policy\022L\n\010outcomes\030\006 \003" +
      "(\01320.aserto.authorizer.v2.api.Decision.O" +
      "utcomesEntryR\010outcomes\0223\n\010resource\030\007 \001(\013" +
      "2\027.google.protobuf.StructR\010resource\022U\n\013a" +
      "nnotations\030\010 \003(\01323.aserto.authorizer.v2." +
      "api.Decision.AnnotationsEntryR\013annotatio" +
      "ns\032;\n\rOutcomesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n" +
      "\005value\030\002 \001(\010R\005value:\0028\001\032>\n\020AnnotationsEn" +
      "try\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005va" +
      "lue:\0028\001\"y\n\014DecisionUser\022C\n\007context\030\001 \001(\013" +
      "2).aserto.authorizer.v2.api.IdentityCont" +
      "extR\007context\022\016\n\002id\030\002 \001(\tR\002id\022\024\n\005email\030\003 " +
      "\001(\tR\005email\"\361\001\n\016DecisionPolicy\022A\n\007context" +
      "\030\001 \001(\0132\'.aserto.authorizer.v2.api.Policy" +
      "ContextR\007context\022)\n\020registry_service\030\002 \001" +
      "(\tR\017registryService\022%\n\016registry_image\030\003 " +
      "\001(\tR\rregistryImage\022!\n\014registry_tag\030\004 \001(\t" +
      "R\013registryTag\022\'\n\017registry_digest\030\005 \001(\tR\016" +
      "registryDigestB\374\001\n\034com.aserto.authorizer" +
      ".v2.apiB\021DecisionLogsProtoH\002P\001Z@github.c" +
      "om/aserto-dev/go-authorizer/aserto/autho" +
      "rizer/v2/api;api\370\001\000\242\002\004AAVA\252\002\030Aserto.Auth" +
      "orizer.V2.Api\312\002\030Aserto\\Authorizer\\V2\\Api" +
      "\342\002$Aserto\\Authorizer\\V2\\Api\\GPBMetadata\352" +
      "\002\033Aserto::Authorizer::V2::Apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.aserto.authorizer.v2.api.PolicyContextProto.getDescriptor(),
          com.aserto.authorizer.v2.api.IdentityContextProto.getDescriptor(),
        });
    internal_static_aserto_authorizer_v2_api_Decision_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aserto_authorizer_v2_api_Decision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_Decision_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Path", "User", "Policy", "Outcomes", "Resource", "Annotations", });
    internal_static_aserto_authorizer_v2_api_Decision_OutcomesEntry_descriptor =
      internal_static_aserto_authorizer_v2_api_Decision_descriptor.getNestedTypes().get(0);
    internal_static_aserto_authorizer_v2_api_Decision_OutcomesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_Decision_OutcomesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_aserto_authorizer_v2_api_Decision_AnnotationsEntry_descriptor =
      internal_static_aserto_authorizer_v2_api_Decision_descriptor.getNestedTypes().get(1);
    internal_static_aserto_authorizer_v2_api_Decision_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_Decision_AnnotationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_aserto_authorizer_v2_api_DecisionUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aserto_authorizer_v2_api_DecisionUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_DecisionUser_descriptor,
        new java.lang.String[] { "Context", "Id", "Email", });
    internal_static_aserto_authorizer_v2_api_DecisionPolicy_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aserto_authorizer_v2_api_DecisionPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_authorizer_v2_api_DecisionPolicy_descriptor,
        new java.lang.String[] { "Context", "RegistryService", "RegistryImage", "RegistryTag", "RegistryDigest", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.aserto.authorizer.v2.api.PolicyContextProto.getDescriptor();
    com.aserto.authorizer.v2.api.IdentityContextProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
