// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/api/module.proto

package com.aserto.authorizer.v2.api;

/**
 * Protobuf type {@code aserto.authorizer.v2.api.Module}
 */
public final class Module extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.api.Module)
    ModuleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Module.newBuilder() to construct.
  private Module(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Module() {
    id_ = "";
    raw_ = "";
    packagePath_ = "";
    packageRoot_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Module();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.api.ModuleProto.internal_static_aserto_authorizer_v2_api_Module_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.api.ModuleProto.internal_static_aserto_authorizer_v2_api_Module_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.api.Module.class, com.aserto.authorizer.v2.api.Module.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>optional string id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RAW_FIELD_NUMBER = 2;
  private volatile java.lang.Object raw_;
  /**
   * <code>optional string raw = 2 [json_name = "raw"];</code>
   * @return Whether the raw field is set.
   */
  @java.lang.Override
  public boolean hasRaw() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string raw = 2 [json_name = "raw"];</code>
   * @return The raw.
   */
  @java.lang.Override
  public java.lang.String getRaw() {
    java.lang.Object ref = raw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      raw_ = s;
      return s;
    }
  }
  /**
   * <code>optional string raw = 2 [json_name = "raw"];</code>
   * @return The bytes for raw.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRawBytes() {
    java.lang.Object ref = raw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      raw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_PATH_FIELD_NUMBER = 3;
  private volatile java.lang.Object packagePath_;
  /**
   * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
   * @return Whether the packagePath field is set.
   */
  @java.lang.Override
  public boolean hasPackagePath() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
   * @return The packagePath.
   */
  @java.lang.Override
  public java.lang.String getPackagePath() {
    java.lang.Object ref = packagePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packagePath_ = s;
      return s;
    }
  }
  /**
   * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
   * @return The bytes for packagePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackagePathBytes() {
    java.lang.Object ref = packagePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packagePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AST_FIELD_NUMBER = 4;
  private com.google.protobuf.Value ast_;
  /**
   * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
   * @return Whether the ast field is set.
   */
  @java.lang.Override
  public boolean hasAst() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
   * @return The ast.
   */
  @java.lang.Override
  public com.google.protobuf.Value getAst() {
    return ast_ == null ? com.google.protobuf.Value.getDefaultInstance() : ast_;
  }
  /**
   * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ValueOrBuilder getAstOrBuilder() {
    return ast_ == null ? com.google.protobuf.Value.getDefaultInstance() : ast_;
  }

  public static final int PACKAGE_ROOT_FIELD_NUMBER = 5;
  private volatile java.lang.Object packageRoot_;
  /**
   * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
   * @return Whether the packageRoot field is set.
   */
  @java.lang.Override
  public boolean hasPackageRoot() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
   * @return The packageRoot.
   */
  @java.lang.Override
  public java.lang.String getPackageRoot() {
    java.lang.Object ref = packageRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageRoot_ = s;
      return s;
    }
  }
  /**
   * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
   * @return The bytes for packageRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageRootBytes() {
    java.lang.Object ref = packageRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static com.aserto.authorizer.v2.api.Module parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.api.Module parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.api.Module parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.api.Module parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.api.Module prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.api.Module}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.api.Module)
      com.aserto.authorizer.v2.api.ModuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.api.ModuleProto.internal_static_aserto_authorizer_v2_api_Module_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.api.ModuleProto.internal_static_aserto_authorizer_v2_api_Module_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.api.Module.class, com.aserto.authorizer.v2.api.Module.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.api.Module.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAstFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      raw_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      packagePath_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (astBuilder_ == null) {
        ast_ = null;
      } else {
        astBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      packageRoot_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.api.ModuleProto.internal_static_aserto_authorizer_v2_api_Module_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.api.Module getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.api.Module.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.api.Module build() {
      com.aserto.authorizer.v2.api.Module result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.api.Module buildPartial() {
      com.aserto.authorizer.v2.api.Module result = new com.aserto.authorizer.v2.api.Module(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.raw_ = raw_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.packagePath_ = packagePath_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (astBuilder_ == null) {
          result.ast_ = ast_;
        } else {
          result.ast_ = astBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.packageRoot_ = packageRoot_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object raw_ = "";
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @return Whether the raw field is set.
     */
    public boolean hasRaw() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @return The raw.
     */
    public java.lang.String getRaw() {
      java.lang.Object ref = raw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        raw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @return The bytes for raw.
     */
    public com.google.protobuf.ByteString
        getRawBytes() {
      java.lang.Object ref = raw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        raw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @param value The raw to set.
     * @return This builder for chaining.
     */
    public Builder setRaw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      raw_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRaw() {
      bitField0_ = (bitField0_ & ~0x00000002);
      raw_ = getDefaultInstance().getRaw();
      onChanged();
      return this;
    }
    /**
     * <code>optional string raw = 2 [json_name = "raw"];</code>
     * @param value The bytes for raw to set.
     * @return This builder for chaining.
     */
    public Builder setRawBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      raw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packagePath_ = "";
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @return Whether the packagePath field is set.
     */
    public boolean hasPackagePath() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @return The packagePath.
     */
    public java.lang.String getPackagePath() {
      java.lang.Object ref = packagePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packagePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @return The bytes for packagePath.
     */
    public com.google.protobuf.ByteString
        getPackagePathBytes() {
      java.lang.Object ref = packagePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @param value The packagePath to set.
     * @return This builder for chaining.
     */
    public Builder setPackagePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      packagePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPackagePath() {
      bitField0_ = (bitField0_ & ~0x00000004);
      packagePath_ = getDefaultInstance().getPackagePath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_path = 3 [json_name = "packagePath"];</code>
     * @param value The bytes for packagePath to set.
     * @return This builder for chaining.
     */
    public Builder setPackagePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      packagePath_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Value ast_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> astBuilder_;
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     * @return Whether the ast field is set.
     */
    public boolean hasAst() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     * @return The ast.
     */
    public com.google.protobuf.Value getAst() {
      if (astBuilder_ == null) {
        return ast_ == null ? com.google.protobuf.Value.getDefaultInstance() : ast_;
      } else {
        return astBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public Builder setAst(com.google.protobuf.Value value) {
      if (astBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ast_ = value;
        onChanged();
      } else {
        astBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public Builder setAst(
        com.google.protobuf.Value.Builder builderForValue) {
      if (astBuilder_ == null) {
        ast_ = builderForValue.build();
        onChanged();
      } else {
        astBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public Builder mergeAst(com.google.protobuf.Value value) {
      if (astBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            ast_ != null &&
            ast_ != com.google.protobuf.Value.getDefaultInstance()) {
          ast_ =
            com.google.protobuf.Value.newBuilder(ast_).mergeFrom(value).buildPartial();
        } else {
          ast_ = value;
        }
        onChanged();
      } else {
        astBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public Builder clearAst() {
      if (astBuilder_ == null) {
        ast_ = null;
        onChanged();
      } else {
        astBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public com.google.protobuf.Value.Builder getAstBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getAstFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    public com.google.protobuf.ValueOrBuilder getAstOrBuilder() {
      if (astBuilder_ != null) {
        return astBuilder_.getMessageOrBuilder();
      } else {
        return ast_ == null ?
            com.google.protobuf.Value.getDefaultInstance() : ast_;
      }
    }
    /**
     * <code>optional .google.protobuf.Value ast = 4 [json_name = "ast"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
        getAstFieldBuilder() {
      if (astBuilder_ == null) {
        astBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                getAst(),
                getParentForChildren(),
                isClean());
        ast_ = null;
      }
      return astBuilder_;
    }

    private java.lang.Object packageRoot_ = "";
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @return Whether the packageRoot field is set.
     */
    public boolean hasPackageRoot() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @return The packageRoot.
     */
    public java.lang.String getPackageRoot() {
      java.lang.Object ref = packageRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @return The bytes for packageRoot.
     */
    public com.google.protobuf.ByteString
        getPackageRootBytes() {
      java.lang.Object ref = packageRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @param value The packageRoot to set.
     * @return This builder for chaining.
     */
    public Builder setPackageRoot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      packageRoot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageRoot() {
      bitField0_ = (bitField0_ & ~0x00000010);
      packageRoot_ = getDefaultInstance().getPackageRoot();
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_root = 5 [json_name = "packageRoot"];</code>
     * @param value The bytes for packageRoot to set.
     * @return This builder for chaining.
     */
    public Builder setPackageRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      packageRoot_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.api.Module)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.api.Module)
  private static final com.aserto.authorizer.v2.api.Module DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.api.Module();
  }

  public static com.aserto.authorizer.v2.api.Module getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Module>
      PARSER = new com.google.protobuf.AbstractParser<Module>() {
    @java.lang.Override
    public Module parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Module> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Module> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.api.Module getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

