// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

// Protobuf Java Version: 3.25.1
package com.aserto.authorizer.v2;

public interface GetPolicyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.authorizer.v2.GetPolicyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   * @return The result.
   */
  com.aserto.authorizer.v2.api.Module getResult();
  /**
   * <code>.aserto.authorizer.v2.api.Module result = 1 [json_name = "result"];</code>
   */
  com.aserto.authorizer.v2.api.ModuleOrBuilder getResultOrBuilder();
}
