// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

// Protobuf Java Version: 3.25.3
package com.aserto.authorizer.v2;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.authorizer.v2.InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string commit = 2 [json_name = "commit"];</code>
   * @return The commit.
   */
  java.lang.String getCommit();
  /**
   * <code>string commit = 2 [json_name = "commit"];</code>
   * @return The bytes for commit.
   */
  com.google.protobuf.ByteString
      getCommitBytes();

  /**
   * <code>string date = 3 [json_name = "date"];</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3 [json_name = "date"];</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string os = 4 [json_name = "os"];</code>
   * @return The os.
   */
  java.lang.String getOs();
  /**
   * <code>string os = 4 [json_name = "os"];</code>
   * @return The bytes for os.
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <code>string arch = 5 [json_name = "arch"];</code>
   * @return The arch.
   */
  java.lang.String getArch();
  /**
   * <code>string arch = 5 [json_name = "arch"];</code>
   * @return The bytes for arch.
   */
  com.google.protobuf.ByteString
      getArchBytes();
}
