// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

// Protobuf Java Version: 3.25.0
package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.ListPoliciesRequest}
 */
public final class ListPoliciesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.ListPoliciesRequest)
    ListPoliciesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListPoliciesRequest.newBuilder() to construct.
  private ListPoliciesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListPoliciesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListPoliciesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.ListPoliciesRequest.class, com.aserto.authorizer.v2.ListPoliciesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FIELD_MASK_FIELD_NUMBER = 1;
  private com.google.protobuf.FieldMask fieldMask_;
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   * @return Whether the fieldMask field is set.
   */
  @java.lang.Override
  public boolean hasFieldMask() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   * @return The fieldMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getFieldMask() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }
  /**
   * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }

  public static final int POLICY_INSTANCE_FIELD_NUMBER = 2;
  private com.aserto.authorizer.v2.api.PolicyInstance policyInstance_;
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   * @return Whether the policyInstance field is set.
   */
  @java.lang.Override
  public boolean hasPolicyInstance() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   * @return The policyInstance.
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.PolicyInstance getPolicyInstance() {
    return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
  }
  /**
   * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
   */
  @java.lang.Override
  public com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder getPolicyInstanceOrBuilder() {
    return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getFieldMask());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPolicyInstance());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFieldMask());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPolicyInstance());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aserto.authorizer.v2.ListPoliciesRequest)) {
      return super.equals(obj);
    }
    com.aserto.authorizer.v2.ListPoliciesRequest other = (com.aserto.authorizer.v2.ListPoliciesRequest) obj;

    if (hasFieldMask() != other.hasFieldMask()) return false;
    if (hasFieldMask()) {
      if (!getFieldMask()
          .equals(other.getFieldMask())) return false;
    }
    if (hasPolicyInstance() != other.hasPolicyInstance()) return false;
    if (hasPolicyInstance()) {
      if (!getPolicyInstance()
          .equals(other.getPolicyInstance())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFieldMask()) {
      hash = (37 * hash) + FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getFieldMask().hashCode();
    }
    if (hasPolicyInstance()) {
      hash = (37 * hash) + POLICY_INSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getPolicyInstance().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.ListPoliciesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.ListPoliciesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.ListPoliciesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.ListPoliciesRequest)
      com.aserto.authorizer.v2.ListPoliciesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.ListPoliciesRequest.class, com.aserto.authorizer.v2.ListPoliciesRequest.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.ListPoliciesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldMaskFieldBuilder();
        getPolicyInstanceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fieldMask_ = null;
      if (fieldMaskBuilder_ != null) {
        fieldMaskBuilder_.dispose();
        fieldMaskBuilder_ = null;
      }
      policyInstance_ = null;
      if (policyInstanceBuilder_ != null) {
        policyInstanceBuilder_.dispose();
        policyInstanceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_ListPoliciesRequest_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.ListPoliciesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest build() {
      com.aserto.authorizer.v2.ListPoliciesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.ListPoliciesRequest buildPartial() {
      com.aserto.authorizer.v2.ListPoliciesRequest result = new com.aserto.authorizer.v2.ListPoliciesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aserto.authorizer.v2.ListPoliciesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fieldMask_ = fieldMaskBuilder_ == null
            ? fieldMask_
            : fieldMaskBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.policyInstance_ = policyInstanceBuilder_ == null
            ? policyInstance_
            : policyInstanceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aserto.authorizer.v2.ListPoliciesRequest) {
        return mergeFrom((com.aserto.authorizer.v2.ListPoliciesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aserto.authorizer.v2.ListPoliciesRequest other) {
      if (other == com.aserto.authorizer.v2.ListPoliciesRequest.getDefaultInstance()) return this;
      if (other.hasFieldMask()) {
        mergeFieldMask(other.getFieldMask());
      }
      if (other.hasPolicyInstance()) {
        mergePolicyInstance(other.getPolicyInstance());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFieldMaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPolicyInstanceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.FieldMask fieldMask_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> fieldMaskBuilder_;
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     * @return Whether the fieldMask field is set.
     */
    public boolean hasFieldMask() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     * @return The fieldMask.
     */
    public com.google.protobuf.FieldMask getFieldMask() {
      if (fieldMaskBuilder_ == null) {
        return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      } else {
        return fieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder setFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldMask_ = value;
      } else {
        fieldMaskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder setFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = builderForValue.build();
      } else {
        fieldMaskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder mergeFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          fieldMask_ != null &&
          fieldMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
          getFieldMaskBuilder().mergeFrom(value);
        } else {
          fieldMask_ = value;
        }
      } else {
        fieldMaskBuilder_.mergeFrom(value);
      }
      if (fieldMask_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public Builder clearFieldMask() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fieldMask_ = null;
      if (fieldMaskBuilder_ != null) {
        fieldMaskBuilder_.dispose();
        fieldMaskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public com.google.protobuf.FieldMask.Builder getFieldMaskBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
      if (fieldMaskBuilder_ != null) {
        return fieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return fieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      }
    }
    /**
     * <code>.google.protobuf.FieldMask field_mask = 1 [json_name = "fieldMask"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getFieldMaskFieldBuilder() {
      if (fieldMaskBuilder_ == null) {
        fieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getFieldMask(),
                getParentForChildren(),
                isClean());
        fieldMask_ = null;
      }
      return fieldMaskBuilder_;
    }

    private com.aserto.authorizer.v2.api.PolicyInstance policyInstance_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder> policyInstanceBuilder_;
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     * @return Whether the policyInstance field is set.
     */
    public boolean hasPolicyInstance() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     * @return The policyInstance.
     */
    public com.aserto.authorizer.v2.api.PolicyInstance getPolicyInstance() {
      if (policyInstanceBuilder_ == null) {
        return policyInstance_ == null ? com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
      } else {
        return policyInstanceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder setPolicyInstance(com.aserto.authorizer.v2.api.PolicyInstance value) {
      if (policyInstanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        policyInstance_ = value;
      } else {
        policyInstanceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder setPolicyInstance(
        com.aserto.authorizer.v2.api.PolicyInstance.Builder builderForValue) {
      if (policyInstanceBuilder_ == null) {
        policyInstance_ = builderForValue.build();
      } else {
        policyInstanceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder mergePolicyInstance(com.aserto.authorizer.v2.api.PolicyInstance value) {
      if (policyInstanceBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          policyInstance_ != null &&
          policyInstance_ != com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance()) {
          getPolicyInstanceBuilder().mergeFrom(value);
        } else {
          policyInstance_ = value;
        }
      } else {
        policyInstanceBuilder_.mergeFrom(value);
      }
      if (policyInstance_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public Builder clearPolicyInstance() {
      bitField0_ = (bitField0_ & ~0x00000002);
      policyInstance_ = null;
      if (policyInstanceBuilder_ != null) {
        policyInstanceBuilder_.dispose();
        policyInstanceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public com.aserto.authorizer.v2.api.PolicyInstance.Builder getPolicyInstanceBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPolicyInstanceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    public com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder getPolicyInstanceOrBuilder() {
      if (policyInstanceBuilder_ != null) {
        return policyInstanceBuilder_.getMessageOrBuilder();
      } else {
        return policyInstance_ == null ?
            com.aserto.authorizer.v2.api.PolicyInstance.getDefaultInstance() : policyInstance_;
      }
    }
    /**
     * <code>optional .aserto.authorizer.v2.api.PolicyInstance policy_instance = 2 [json_name = "policyInstance"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder> 
        getPolicyInstanceFieldBuilder() {
      if (policyInstanceBuilder_ == null) {
        policyInstanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aserto.authorizer.v2.api.PolicyInstance, com.aserto.authorizer.v2.api.PolicyInstance.Builder, com.aserto.authorizer.v2.api.PolicyInstanceOrBuilder>(
                getPolicyInstance(),
                getParentForChildren(),
                isClean());
        policyInstance_ = null;
      }
      return policyInstanceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.ListPoliciesRequest)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.ListPoliciesRequest)
  private static final com.aserto.authorizer.v2.ListPoliciesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.ListPoliciesRequest();
  }

  public static com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPoliciesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListPoliciesRequest>() {
    @java.lang.Override
    public ListPoliciesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListPoliciesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPoliciesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.ListPoliciesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

