// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: aserto/authorizer/v2/authorizer.proto
// Protobuf Java Version: 4.27.1

package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.QueryResponse}
 */
public final class QueryResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.QueryResponse)
    QueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      QueryResponse.class.getName());
  }
  // Use QueryResponse.newBuilder() to construct.
  private QueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private QueryResponse() {
    trace_ = java.util.Collections.emptyList();
    traceSummary_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.QueryResponse.class, com.aserto.authorizer.v2.QueryResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RESPONSE_FIELD_NUMBER = 1;
  private com.google.protobuf.Struct response_;
  /**
   * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
   * @return The response.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getResponse() {
    return response_ == null ? com.google.protobuf.Struct.getDefaultInstance() : response_;
  }
  /**
   * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getResponseOrBuilder() {
    return response_ == null ? com.google.protobuf.Struct.getDefaultInstance() : response_;
  }

  public static final int METRICS_FIELD_NUMBER = 2;
  private com.google.protobuf.Struct metrics_;
  /**
   * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
   * @return Whether the metrics field is set.
   */
  @java.lang.Override
  public boolean hasMetrics() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
   * @return The metrics.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetrics() {
    return metrics_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metrics_;
  }
  /**
   * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetricsOrBuilder() {
    return metrics_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metrics_;
  }

  public static final int TRACE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Struct> trace_;
  /**
   * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Struct> getTraceList() {
    return trace_;
  }
  /**
   * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.StructOrBuilder> 
      getTraceOrBuilderList() {
    return trace_;
  }
  /**
   * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public int getTraceCount() {
    return trace_.size();
  }
  /**
   * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Struct getTrace(int index) {
    return trace_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getTraceOrBuilder(
      int index) {
    return trace_.get(index);
  }

  public static final int TRACE_SUMMARY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList traceSummary_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
   * @return A list containing the traceSummary.
   */
  public com.google.protobuf.ProtocolStringList
      getTraceSummaryList() {
    return traceSummary_;
  }
  /**
   * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
   * @return The count of traceSummary.
   */
  public int getTraceSummaryCount() {
    return traceSummary_.size();
  }
  /**
   * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
   * @param index The index of the element to return.
   * @return The traceSummary at the given index.
   */
  public java.lang.String getTraceSummary(int index) {
    return traceSummary_.get(index);
  }
  /**
   * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the traceSummary at the given index.
   */
  public com.google.protobuf.ByteString
      getTraceSummaryBytes(int index) {
    return traceSummary_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getMetrics());
    }
    for (int i = 0; i < trace_.size(); i++) {
      output.writeMessage(3, trace_.get(i));
    }
    for (int i = 0; i < traceSummary_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, traceSummary_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetrics());
    }
    for (int i = 0; i < trace_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, trace_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < traceSummary_.size(); i++) {
        dataSize += computeStringSizeNoTag(traceSummary_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTraceSummaryList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aserto.authorizer.v2.QueryResponse)) {
      return super.equals(obj);
    }
    com.aserto.authorizer.v2.QueryResponse other = (com.aserto.authorizer.v2.QueryResponse) obj;

    if (hasResponse() != other.hasResponse()) return false;
    if (hasResponse()) {
      if (!getResponse()
          .equals(other.getResponse())) return false;
    }
    if (hasMetrics() != other.hasMetrics()) return false;
    if (hasMetrics()) {
      if (!getMetrics()
          .equals(other.getMetrics())) return false;
    }
    if (!getTraceList()
        .equals(other.getTraceList())) return false;
    if (!getTraceSummaryList()
        .equals(other.getTraceSummaryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResponse()) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
    }
    if (hasMetrics()) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetrics().hashCode();
    }
    if (getTraceCount() > 0) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTraceList().hashCode();
    }
    if (getTraceSummaryCount() > 0) {
      hash = (37 * hash) + TRACE_SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getTraceSummaryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.authorizer.v2.QueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.authorizer.v2.QueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.QueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.QueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.QueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.QueryResponse)
      com.aserto.authorizer.v2.QueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.QueryResponse.class, com.aserto.authorizer.v2.QueryResponse.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.QueryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getResponseFieldBuilder();
        getMetricsFieldBuilder();
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      if (traceBuilder_ == null) {
        trace_ = java.util.Collections.emptyList();
      } else {
        trace_ = null;
        traceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      traceSummary_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryResponse_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryResponse getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.QueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryResponse build() {
      com.aserto.authorizer.v2.QueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryResponse buildPartial() {
      com.aserto.authorizer.v2.QueryResponse result = new com.aserto.authorizer.v2.QueryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aserto.authorizer.v2.QueryResponse result) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          trace_ = java.util.Collections.unmodifiableList(trace_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.trace_ = trace_;
      } else {
        result.trace_ = traceBuilder_.build();
      }
    }

    private void buildPartial0(com.aserto.authorizer.v2.QueryResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.response_ = responseBuilder_ == null
            ? response_
            : responseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.metrics_ = metricsBuilder_ == null
            ? metrics_
            : metricsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        traceSummary_.makeImmutable();
        result.traceSummary_ = traceSummary_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aserto.authorizer.v2.QueryResponse) {
        return mergeFrom((com.aserto.authorizer.v2.QueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aserto.authorizer.v2.QueryResponse other) {
      if (other == com.aserto.authorizer.v2.QueryResponse.getDefaultInstance()) return this;
      if (other.hasResponse()) {
        mergeResponse(other.getResponse());
      }
      if (other.hasMetrics()) {
        mergeMetrics(other.getMetrics());
      }
      if (traceBuilder_ == null) {
        if (!other.trace_.isEmpty()) {
          if (trace_.isEmpty()) {
            trace_ = other.trace_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTraceIsMutable();
            trace_.addAll(other.trace_);
          }
          onChanged();
        }
      } else {
        if (!other.trace_.isEmpty()) {
          if (traceBuilder_.isEmpty()) {
            traceBuilder_.dispose();
            traceBuilder_ = null;
            trace_ = other.trace_;
            bitField0_ = (bitField0_ & ~0x00000004);
            traceBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTraceFieldBuilder() : null;
          } else {
            traceBuilder_.addAllMessages(other.trace_);
          }
        }
      }
      if (!other.traceSummary_.isEmpty()) {
        if (traceSummary_.isEmpty()) {
          traceSummary_ = other.traceSummary_;
          bitField0_ |= 0x00000008;
        } else {
          ensureTraceSummaryIsMutable();
          traceSummary_.addAll(other.traceSummary_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetricsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.Struct m =
                  input.readMessage(
                      com.google.protobuf.Struct.parser(),
                      extensionRegistry);
              if (traceBuilder_ == null) {
                ensureTraceIsMutable();
                trace_.add(m);
              } else {
                traceBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTraceSummaryIsMutable();
              traceSummary_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Struct response_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> responseBuilder_;
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     * @return The response.
     */
    public com.google.protobuf.Struct getResponse() {
      if (responseBuilder_ == null) {
        return response_ == null ? com.google.protobuf.Struct.getDefaultInstance() : response_;
      } else {
        return responseBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public Builder setResponse(com.google.protobuf.Struct value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
      } else {
        responseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public Builder setResponse(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (responseBuilder_ == null) {
        response_ = builderForValue.build();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public Builder mergeResponse(com.google.protobuf.Struct value) {
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          response_ != null &&
          response_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getResponseBuilder().mergeFrom(value);
        } else {
          response_ = value;
        }
      } else {
        responseBuilder_.mergeFrom(value);
      }
      if (response_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public com.google.protobuf.Struct.Builder getResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    public com.google.protobuf.StructOrBuilder getResponseOrBuilder() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        return response_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : response_;
      }
    }
    /**
     * <code>.google.protobuf.Struct response = 1 [json_name = "response"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getResponse(),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }

    private com.google.protobuf.Struct metrics_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metricsBuilder_;
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     * @return Whether the metrics field is set.
     */
    public boolean hasMetrics() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     * @return The metrics.
     */
    public com.google.protobuf.Struct getMetrics() {
      if (metricsBuilder_ == null) {
        return metrics_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metrics_;
      } else {
        return metricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public Builder setMetrics(com.google.protobuf.Struct value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metrics_ = value;
      } else {
        metricsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public Builder setMetrics(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        metrics_ = builderForValue.build();
      } else {
        metricsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public Builder mergeMetrics(com.google.protobuf.Struct value) {
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          metrics_ != null &&
          metrics_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetricsBuilder().mergeFrom(value);
        } else {
          metrics_ = value;
        }
      } else {
        metricsBuilder_.mergeFrom(value);
      }
      if (metrics_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public Builder clearMetrics() {
      bitField0_ = (bitField0_ & ~0x00000002);
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public com.google.protobuf.Struct.Builder getMetricsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    public com.google.protobuf.StructOrBuilder getMetricsOrBuilder() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilder();
      } else {
        return metrics_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metrics_;
      }
    }
    /**
     * <code>.google.protobuf.Struct metrics = 2 [json_name = "metrics"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetrics(),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }

    private java.util.List<com.google.protobuf.Struct> trace_ =
      java.util.Collections.emptyList();
    private void ensureTraceIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        trace_ = new java.util.ArrayList<com.google.protobuf.Struct>(trace_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> traceBuilder_;

    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public java.util.List<com.google.protobuf.Struct> getTraceList() {
      if (traceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trace_);
      } else {
        return traceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public int getTraceCount() {
      if (traceBuilder_ == null) {
        return trace_.size();
      } else {
        return traceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public com.google.protobuf.Struct getTrace(int index) {
      if (traceBuilder_ == null) {
        return trace_.get(index);
      } else {
        return traceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder setTrace(
        int index, com.google.protobuf.Struct value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTraceIsMutable();
        trace_.set(index, value);
        onChanged();
      } else {
        traceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder setTrace(
        int index, com.google.protobuf.Struct.Builder builderForValue) {
      if (traceBuilder_ == null) {
        ensureTraceIsMutable();
        trace_.set(index, builderForValue.build());
        onChanged();
      } else {
        traceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder addTrace(com.google.protobuf.Struct value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTraceIsMutable();
        trace_.add(value);
        onChanged();
      } else {
        traceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder addTrace(
        int index, com.google.protobuf.Struct value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTraceIsMutable();
        trace_.add(index, value);
        onChanged();
      } else {
        traceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder addTrace(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (traceBuilder_ == null) {
        ensureTraceIsMutable();
        trace_.add(builderForValue.build());
        onChanged();
      } else {
        traceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder addTrace(
        int index, com.google.protobuf.Struct.Builder builderForValue) {
      if (traceBuilder_ == null) {
        ensureTraceIsMutable();
        trace_.add(index, builderForValue.build());
        onChanged();
      } else {
        traceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder addAllTrace(
        java.lang.Iterable<? extends com.google.protobuf.Struct> values) {
      if (traceBuilder_ == null) {
        ensureTraceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trace_);
        onChanged();
      } else {
        traceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder clearTrace() {
      if (traceBuilder_ == null) {
        trace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        traceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public Builder removeTrace(int index) {
      if (traceBuilder_ == null) {
        ensureTraceIsMutable();
        trace_.remove(index);
        onChanged();
      } else {
        traceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public com.google.protobuf.Struct.Builder getTraceBuilder(
        int index) {
      return getTraceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public com.google.protobuf.StructOrBuilder getTraceOrBuilder(
        int index) {
      if (traceBuilder_ == null) {
        return trace_.get(index);  } else {
        return traceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public java.util.List<? extends com.google.protobuf.StructOrBuilder> 
         getTraceOrBuilderList() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trace_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public com.google.protobuf.Struct.Builder addTraceBuilder() {
      return getTraceFieldBuilder().addBuilder(
          com.google.protobuf.Struct.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public com.google.protobuf.Struct.Builder addTraceBuilder(
        int index) {
      return getTraceFieldBuilder().addBuilder(
          index, com.google.protobuf.Struct.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Struct trace = 3 [json_name = "trace"];</code>
     */
    public java.util.List<com.google.protobuf.Struct.Builder> 
         getTraceBuilderList() {
      return getTraceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                trace_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList traceSummary_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTraceSummaryIsMutable() {
      if (!traceSummary_.isModifiable()) {
        traceSummary_ = new com.google.protobuf.LazyStringArrayList(traceSummary_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @return A list containing the traceSummary.
     */
    public com.google.protobuf.ProtocolStringList
        getTraceSummaryList() {
      traceSummary_.makeImmutable();
      return traceSummary_;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @return The count of traceSummary.
     */
    public int getTraceSummaryCount() {
      return traceSummary_.size();
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param index The index of the element to return.
     * @return The traceSummary at the given index.
     */
    public java.lang.String getTraceSummary(int index) {
      return traceSummary_.get(index);
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the traceSummary at the given index.
     */
    public com.google.protobuf.ByteString
        getTraceSummaryBytes(int index) {
      return traceSummary_.getByteString(index);
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param index The index to set the value at.
     * @param value The traceSummary to set.
     * @return This builder for chaining.
     */
    public Builder setTraceSummary(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTraceSummaryIsMutable();
      traceSummary_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param value The traceSummary to add.
     * @return This builder for chaining.
     */
    public Builder addTraceSummary(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTraceSummaryIsMutable();
      traceSummary_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param values The traceSummary to add.
     * @return This builder for chaining.
     */
    public Builder addAllTraceSummary(
        java.lang.Iterable<java.lang.String> values) {
      ensureTraceSummaryIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, traceSummary_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceSummary() {
      traceSummary_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param value The bytes of the traceSummary to add.
     * @return This builder for chaining.
     */
    public Builder addTraceSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTraceSummaryIsMutable();
      traceSummary_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.QueryResponse)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.QueryResponse)
  private static final com.aserto.authorizer.v2.QueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.QueryResponse();
  }

  public static com.aserto.authorizer.v2.QueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueryResponse>() {
    @java.lang.Override
    public QueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.QueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

