// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

// Protobuf Java Version: 3.25.3
package com.aserto.authorizer.v2;

public interface QueryOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.authorizer.v2.QueryOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool metrics = 1 [json_name = "metrics"];</code>
   * @return The metrics.
   */
  boolean getMetrics();

  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool instrument = 2 [json_name = "instrument"];</code>
   * @return The instrument.
   */
  boolean getInstrument();

  /**
   * <pre>
   * default ExplainOffV1
   * </pre>
   *
   * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
   * @return The enum numeric value on the wire for trace.
   */
  int getTraceValue();
  /**
   * <pre>
   * default ExplainOffV1
   * </pre>
   *
   * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
   * @return The trace.
   */
  com.aserto.authorizer.v2.TraceLevel getTrace();

  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool trace_summary = 4 [json_name = "traceSummary"];</code>
   * @return The traceSummary.
   */
  boolean getTraceSummary();
}
