// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/authorizer/v2/authorizer.proto

package com.aserto.authorizer.v2;

/**
 * Protobuf type {@code aserto.authorizer.v2.QueryOptions}
 */
public final class QueryOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.authorizer.v2.QueryOptions)
    QueryOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryOptions.newBuilder() to construct.
  private QueryOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryOptions() {
    trace_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryOptions();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.authorizer.v2.QueryOptions.class, com.aserto.authorizer.v2.QueryOptions.Builder.class);
  }

  public static final int METRICS_FIELD_NUMBER = 1;
  private boolean metrics_ = false;
  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool metrics = 1 [json_name = "metrics"];</code>
   * @return The metrics.
   */
  @java.lang.Override
  public boolean getMetrics() {
    return metrics_;
  }

  public static final int INSTRUMENT_FIELD_NUMBER = 2;
  private boolean instrument_ = false;
  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool instrument = 2 [json_name = "instrument"];</code>
   * @return The instrument.
   */
  @java.lang.Override
  public boolean getInstrument() {
    return instrument_;
  }

  public static final int TRACE_FIELD_NUMBER = 3;
  private int trace_ = 0;
  /**
   * <pre>
   * default ExplainOffV1
   * </pre>
   *
   * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
   * @return The enum numeric value on the wire for trace.
   */
  @java.lang.Override public int getTraceValue() {
    return trace_;
  }
  /**
   * <pre>
   * default ExplainOffV1
   * </pre>
   *
   * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
   * @return The trace.
   */
  @java.lang.Override public com.aserto.authorizer.v2.TraceLevel getTrace() {
    com.aserto.authorizer.v2.TraceLevel result = com.aserto.authorizer.v2.TraceLevel.forNumber(trace_);
    return result == null ? com.aserto.authorizer.v2.TraceLevel.UNRECOGNIZED : result;
  }

  public static final int TRACE_SUMMARY_FIELD_NUMBER = 4;
  private boolean traceSummary_ = false;
  /**
   * <pre>
   * default false
   * </pre>
   *
   * <code>bool trace_summary = 4 [json_name = "traceSummary"];</code>
   * @return The traceSummary.
   */
  @java.lang.Override
  public boolean getTraceSummary() {
    return traceSummary_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metrics_ != false) {
      output.writeBool(1, metrics_);
    }
    if (instrument_ != false) {
      output.writeBool(2, instrument_);
    }
    if (trace_ != com.aserto.authorizer.v2.TraceLevel.TRACE_LEVEL_UNKNOWN.getNumber()) {
      output.writeEnum(3, trace_);
    }
    if (traceSummary_ != false) {
      output.writeBool(4, traceSummary_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metrics_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, metrics_);
    }
    if (instrument_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, instrument_);
    }
    if (trace_ != com.aserto.authorizer.v2.TraceLevel.TRACE_LEVEL_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, trace_);
    }
    if (traceSummary_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, traceSummary_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aserto.authorizer.v2.QueryOptions)) {
      return super.equals(obj);
    }
    com.aserto.authorizer.v2.QueryOptions other = (com.aserto.authorizer.v2.QueryOptions) obj;

    if (getMetrics()
        != other.getMetrics()) return false;
    if (getInstrument()
        != other.getInstrument()) return false;
    if (trace_ != other.trace_) return false;
    if (getTraceSummary()
        != other.getTraceSummary()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRICS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMetrics());
    hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInstrument());
    hash = (37 * hash) + TRACE_FIELD_NUMBER;
    hash = (53 * hash) + trace_;
    hash = (37 * hash) + TRACE_SUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTraceSummary());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.authorizer.v2.QueryOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.authorizer.v2.QueryOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.authorizer.v2.QueryOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.authorizer.v2.QueryOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.authorizer.v2.QueryOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.authorizer.v2.QueryOptions)
      com.aserto.authorizer.v2.QueryOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.authorizer.v2.QueryOptions.class, com.aserto.authorizer.v2.QueryOptions.Builder.class);
    }

    // Construct using com.aserto.authorizer.v2.QueryOptions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metrics_ = false;
      instrument_ = false;
      trace_ = 0;
      traceSummary_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.authorizer.v2.AuthorizerProto.internal_static_aserto_authorizer_v2_QueryOptions_descriptor;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryOptions getDefaultInstanceForType() {
      return com.aserto.authorizer.v2.QueryOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryOptions build() {
      com.aserto.authorizer.v2.QueryOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.authorizer.v2.QueryOptions buildPartial() {
      com.aserto.authorizer.v2.QueryOptions result = new com.aserto.authorizer.v2.QueryOptions(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aserto.authorizer.v2.QueryOptions result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metrics_ = metrics_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.instrument_ = instrument_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.trace_ = trace_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.traceSummary_ = traceSummary_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aserto.authorizer.v2.QueryOptions) {
        return mergeFrom((com.aserto.authorizer.v2.QueryOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aserto.authorizer.v2.QueryOptions other) {
      if (other == com.aserto.authorizer.v2.QueryOptions.getDefaultInstance()) return this;
      if (other.getMetrics() != false) {
        setMetrics(other.getMetrics());
      }
      if (other.getInstrument() != false) {
        setInstrument(other.getInstrument());
      }
      if (other.trace_ != 0) {
        setTraceValue(other.getTraceValue());
      }
      if (other.getTraceSummary() != false) {
        setTraceSummary(other.getTraceSummary());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              metrics_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              instrument_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              trace_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              traceSummary_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean metrics_ ;
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool metrics = 1 [json_name = "metrics"];</code>
     * @return The metrics.
     */
    @java.lang.Override
    public boolean getMetrics() {
      return metrics_;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool metrics = 1 [json_name = "metrics"];</code>
     * @param value The metrics to set.
     * @return This builder for chaining.
     */
    public Builder setMetrics(boolean value) {

      metrics_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool metrics = 1 [json_name = "metrics"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMetrics() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metrics_ = false;
      onChanged();
      return this;
    }

    private boolean instrument_ ;
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool instrument = 2 [json_name = "instrument"];</code>
     * @return The instrument.
     */
    @java.lang.Override
    public boolean getInstrument() {
      return instrument_;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool instrument = 2 [json_name = "instrument"];</code>
     * @param value The instrument to set.
     * @return This builder for chaining.
     */
    public Builder setInstrument(boolean value) {

      instrument_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool instrument = 2 [json_name = "instrument"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrument() {
      bitField0_ = (bitField0_ & ~0x00000002);
      instrument_ = false;
      onChanged();
      return this;
    }

    private int trace_ = 0;
    /**
     * <pre>
     * default ExplainOffV1
     * </pre>
     *
     * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
     * @return The enum numeric value on the wire for trace.
     */
    @java.lang.Override public int getTraceValue() {
      return trace_;
    }
    /**
     * <pre>
     * default ExplainOffV1
     * </pre>
     *
     * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
     * @param value The enum numeric value on the wire for trace to set.
     * @return This builder for chaining.
     */
    public Builder setTraceValue(int value) {
      trace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default ExplainOffV1
     * </pre>
     *
     * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
     * @return The trace.
     */
    @java.lang.Override
    public com.aserto.authorizer.v2.TraceLevel getTrace() {
      com.aserto.authorizer.v2.TraceLevel result = com.aserto.authorizer.v2.TraceLevel.forNumber(trace_);
      return result == null ? com.aserto.authorizer.v2.TraceLevel.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * default ExplainOffV1
     * </pre>
     *
     * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
     * @param value The trace to set.
     * @return This builder for chaining.
     */
    public Builder setTrace(com.aserto.authorizer.v2.TraceLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      trace_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default ExplainOffV1
     * </pre>
     *
     * <code>.aserto.authorizer.v2.TraceLevel trace = 3 [json_name = "trace"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000004);
      trace_ = 0;
      onChanged();
      return this;
    }

    private boolean traceSummary_ ;
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool trace_summary = 4 [json_name = "traceSummary"];</code>
     * @return The traceSummary.
     */
    @java.lang.Override
    public boolean getTraceSummary() {
      return traceSummary_;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool trace_summary = 4 [json_name = "traceSummary"];</code>
     * @param value The traceSummary to set.
     * @return This builder for chaining.
     */
    public Builder setTraceSummary(boolean value) {

      traceSummary_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default false
     * </pre>
     *
     * <code>bool trace_summary = 4 [json_name = "traceSummary"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceSummary() {
      bitField0_ = (bitField0_ & ~0x00000008);
      traceSummary_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.authorizer.v2.QueryOptions)
  }

  // @@protoc_insertion_point(class_scope:aserto.authorizer.v2.QueryOptions)
  private static final com.aserto.authorizer.v2.QueryOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.authorizer.v2.QueryOptions();
  }

  public static com.aserto.authorizer.v2.QueryOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryOptions>
      PARSER = new com.google.protobuf.AbstractParser<QueryOptions>() {
    @java.lang.Override
    public QueryOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.authorizer.v2.QueryOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

